ability to scan for a package instead of a port

diff --git a/prmck b/prmck
--- a/prmck
+++ b/prmck
@@ -8,37 +8,40 @@ RED='\033[91m'
 GREEN='\033[92m'
 BOLD='\033[1m'
 NORMAL='\033[0m'
-##################
+################
 PKG=
 PKG_PREV=
 PKG_SCANNED=0
 M_ERR_COUNT=0
 O_ERR_COUNT=0
 FIX=0
+IS_PKG=0
 M_FIXED=0
 O_FIXED=0
 S=s
 
 for arg in "$@"; do
     case $arg in
-        all)       arg='*';;
-        -f|--fix)  FIX=1;;
-        -ff)       FIX=2;;
-        -h|--help) cat << EOL
+        all)                arg='*';;
+        -f|--fix)           FIX=1;;
+        -ff)                FIX=2;;
+        -p|--pkg|--package) IS_PKG=1;;
+        -h|--help)          cat << EOL
 prmck - https://github.com/nggit/prmck
 
 Usage:
-  prmck [options] <port>
+  prmck [options] [<port>/<package>]
 
 Options:
-  -f, --fix     fix file permissions
-  -ff           fix file permissions and ownership
-  -h, --help    see this help
+  -f, --fix               fix file permissions
+  -ff                     fix file permissions and ownership
+  -p, --pkg, --package    a switch to scan for a package instead of a port
+  -h, --help              see this help
 
 Port:
   all, core, opt, etc.
 
-Example: prmck core, prmck -f core, etc.
+Example: prmck core, prmck -f core, prmck -f -p firefox, etc.
 EOL
 exit;;
     esac
@@ -49,6 +52,9 @@ if [ -z "$arg" ]; then
     exit 22
 fi
 
+###########
+# functions
+###########
 parse_mode() {
     u=; g=; o=;
     mode=$1
@@ -90,7 +96,10 @@ parse_owner() {
 }
 
 do_scan() {
+    total=$( printf '%d' "$( grep -cs '/' "$1" )" )
+    count=0
     while IFS= read -r line <&3; do
+        count=$(( count + 1 ))
         file=${line##*$( printf '\t' )}
         file=/${file%% *}
         [ -e "$file" ] || continue
@@ -101,74 +110,94 @@ do_scan() {
         # current state
         mode=$( stat -c '%A' "$file" )
         owner=$( stat -c '%U/%G' "$file" )
-        if [ "$mode" != "$mode_orig" ] || [ "$owner" != "$owner_orig" ]; then
+        printf '\r%b%b %-22s%s' "\033[2K" "${BOLD}Scanning:$NORMAL" "$PKG" "$(( 100 / (total / count) ))%"
+        if [ "$mode" != "$mode_orig" ]; then
+            M_ERR_COUNT=$(( M_ERR_COUNT + 1 ))
             printf '\r%b' "\033[2K"
-            if [ "$mode" != "$mode_orig" ]; then
-                M_ERR_COUNT=$(( M_ERR_COUNT + 1 ))
-                if [ "$PKG" = "$PKG_PREV" ]; then
-                    printf '  %s\t%b\t%s\n' "$mode_orig" "$RED$mode$NORMAL" "$file"
+            if [ "$PKG" = "$PKG_PREV" ]; then
+                printf '  %s\t%b\t%s\n' "$mode_orig" "$RED$mode$NORMAL" "$file"
+            else
+                printf '%b\n  %s\t%b\t%s\n' "$BOLD$PKG:$NORMAL" "$mode_orig" "$RED$mode$NORMAL" "$file"
+                PKG_PREV=$PKG
+            fi
+            if [ $FIX -eq 0 ]; then
+                printf '    Fix permissions? ( 1 = Yes, Enter = No ): '
+                read -r input
+            fi
+            if [ $FIX -gt 0 ] || [ "$input" = 1 ]; then
+                printf '    -> '
+                chmod=$( chmod "$( parse_mode "$mode_orig" )" "$file" 2>&1 )
+                if [ -z "$chmod" ]; then
+                    printf '%b\n' "${GREEN}OK$NORMAL"
+                    M_FIXED=$(( M_FIXED + 1 ))
                 else
-                    printf '%b\n  %s\t%b\t%s\n' "$BOLD$PKG:$NORMAL" "$mode_orig" "$RED$mode$NORMAL" "$file"
-                    PKG_PREV=$PKG
-                fi
-                if [ $FIX -eq 0 ]; then
-                    printf '    Fix permissions? ( y = Yes, Enter = No ): '
-                    read -r input
-                fi
-                if [ $FIX -gt 0 ] || [ "$input" = 'y' ] || [ "$input" = 'Y' ]; then
-                    printf '    Results: '
-                    if chmod "$( parse_mode "$mode_orig" )" "$file"; then
-                        printf '%b\n' "${GREEN}OK$NORMAL"
-                        M_FIXED=$(( M_FIXED + 1 ))
-                    fi
+                    printf 'chmod %s %s; #%s\n' "$( parse_mode "$mode_orig" )" "$file" "${chmod#chmod:}" 1>&2
                 fi
             fi
-            if [ "$owner" != "$owner_orig" ]; then
-                O_ERR_COUNT=$(( O_ERR_COUNT + 1 ))
-                if [ "$PKG" = "$PKG_PREV" ]; then
-                    printf '  %s\t%b\t%s\n' "$owner_orig" "$RED$owner$NORMAL" "$file"
+        fi
+        if [ "$owner" != "$owner_orig" ]; then
+            O_ERR_COUNT=$(( O_ERR_COUNT + 1 ))
+            printf '\r%b' "\033[2K"
+            if [ "$PKG" = "$PKG_PREV" ]; then
+                printf '  %s\t%b\t%s\n' "$owner_orig" "$RED$owner$NORMAL" "$file"
+            else
+                printf '%b\n  %s\t%b\t%s\n' "$BOLD$PKG:$NORMAL" "$owner_orig" "$RED$owner$NORMAL" "$file"
+                PKG_PREV=$PKG
+            fi
+            if [ $FIX -lt 2 ]; then
+                printf '    Fix ownership? ( 1 = Yes, Enter = No ): '
+                read -r input
+            fi
+            if [ $FIX -eq 2 ] || [ "$input" = 1 ]; then
+                printf '    -> '
+                chown=$( chown "$( parse_owner "$owner_orig" )" "$file" 2>&1 )
+                if [ -z "$chown" ]; then
+                    printf '%b\n' "${GREEN}OK$NORMAL"
+                    O_FIXED=$(( O_FIXED + 1 ))
                 else
-                    printf '%b\n  %s\t%b\t%s\n' "$BOLD$PKG:$NORMAL" "$owner_orig" "$RED$owner$NORMAL" "$file"
-                    PKG_PREV=$PKG
-                fi
-                if [ $FIX -lt 2 ]; then
-                    printf '    Fix ownership? ( y = Yes, Enter = No ): '
-                    read -r input
-                fi
-                if [ $FIX -eq 2 ] || [ "$input" = 'y' ] || [ "$input" = 'Y' ]; then
-                    printf '    Results: '
-                    if chown "$( parse_owner "$owner_orig" )" "$file"; then
-                        printf '%b\n' "${GREEN}OK$NORMAL"
-                        O_FIXED=$(( O_FIXED + 1 ))
-                    fi
+                    printf 'chown %s %s; #%s\n' "$( parse_owner "$owner_orig" )" "$file" "${chown#chown:}" 1>&2
                 fi
             fi
         fi
     done 3< "$1"
+    printf '\r%b' "\033[2K"
 }
 
+######
+# scan
+######
 [ "$( id -u )" -eq 0 ] || printf 'Info: Running prmck in safe mode\n\n'
 
-port_dir=
-for prtdir in $( grep -i '^\s*prtdir' /etc/prt-get.conf | sed 's/prtdir//i; s/\s//g' ); do
-    prtdir=${prtdir%/*}
-    [ "$prtdir" = "$port_dir" ] && continue
-    if [ "$arg" != '*' ] && [ ! -d "$prtdir/$arg" ]; then
-        printf '%b: Invalid options or port\n' "${RED}Error$NORMAL";
-        exit 1;
+if [ "$IS_PKG" -eq 1 ]; then
+    PKG=$arg
+    footprint=$( prt-get path "$PKG" 2> /dev/null )/.footprint
+    if [ -f "$footprint" ]; then
+        do_scan "$footprint"
+        PKG_SCANNED=1
     fi
-    for PKG in $( prt-get listinst ); do
-        for footprint in $prtdir/$arg/$PKG/.footprint; do
-            [ -f "$footprint" ] || continue
-            printf '%b %s' "${BOLD}Scanning:$NORMAL" "$PKG"
-            do_scan "$footprint"
-            printf '\r%b' "\033[2K"
-            PKG_SCANNED=$(( PKG_SCANNED + 1 ))
+else
+    port_dir=
+    for prtdir in $( grep -i '^\s*prtdir' /etc/prt-get.conf | sed 's/prtdir//i; s/\s//g' ); do
+        prtdir=${prtdir%/*}
+        [ "$prtdir" = "$port_dir" ] && continue
+        if [ "$arg" != '*' ] && [ ! -d "$prtdir/$arg" ]; then
+            printf '%b: Invalid options or port\n' "${RED}Error$NORMAL";
+            exit 1;
+        fi
+        for PKG in $( prt-get listinst ); do
+            for footprint in $prtdir/$arg/$PKG/.footprint; do
+                [ -f "$footprint" ] || continue
+                do_scan "$footprint"
+                PKG_SCANNED=$(( PKG_SCANNED + 1 ))
+            done
         done
+        port_dir=$prtdir
     done
-    port_dir=$prtdir
-done
+fi
 
+##############
+# scan reports
+##############
 if [ $PKG_SCANNED -gt 0 ]; then
     [ $PKG_SCANNED -eq 1 ] && S=
     n='\n'; [ $M_ERR_COUNT -gt 0 ] || [ $O_ERR_COUNT -gt 0 ] || n=
@@ -177,19 +206,17 @@ else
     printf '%b: The scan was never performed\n' "${RED}Error$NORMAL"
     exit 1
 fi
-if [ $M_ERR_COUNT -gt 0 ] || [ $O_ERR_COUNT -gt 0 ]; then
-    if [ $M_ERR_COUNT -gt 0 ]; then
-        [ $M_ERR_COUNT -eq 1 ] && S=
-        [ $M_FIXED -gt 0 ] && M_FIXED=$GREEN$M_FIXED$NORMAL
-        printf '%b file%s with broken permissions found. %b fixed.\n' "$RED$M_ERR_COUNT$NORMAL" "$S" "$M_FIXED"
-    fi
-    if [ $O_ERR_COUNT -gt 0 ]; then
-        [ $O_ERR_COUNT -eq 1 ] && S=
-        [ $O_FIXED -gt 0 ] && O_FIXED=$GREEN$O_FIXED$NORMAL
-        printf '%b file%s with broken ownership found. %b fixed.\n' "$RED$O_ERR_COUNT$NORMAL" "$S" "$O_FIXED"
-    fi
-else
-    printf '%b. No problems were found.\n' "${GREEN}Good$NORMAL"
+if [ $M_ERR_COUNT -gt 0 ]; then
+    [ $M_ERR_COUNT -eq 1 ] && S=
+    [ $M_FIXED -gt 0 ] && M_FIXED=$GREEN$M_FIXED$NORMAL
+    printf '%b file%s with broken permissions found. %b fixed.\n' "$RED$M_ERR_COUNT$NORMAL" "$S" "$M_FIXED"
 fi
+if [ $O_ERR_COUNT -gt 0 ]; then
+    [ $O_ERR_COUNT -eq 1 ] && S=
+    [ $O_FIXED -gt 0 ] && O_FIXED=$GREEN$O_FIXED$NORMAL
+    printf '%b file%s with broken ownership found. %b fixed.\n' "$RED$O_ERR_COUNT$NORMAL" "$S" "$O_FIXED"
+fi
+
+[ $M_ERR_COUNT -gt 0 ] || [ $O_ERR_COUNT -gt 0 ] || printf '%b. No problems were found.\n' "${GREEN}Good$NORMAL"
 
 exit 0
